import { useMemo, useState } from 'react'
import './App.css'
import { assess, emptyAnswers, formatINR } from './rules'
import type { Answers } from './rules'

type Question = { key: keyof Answers; label: string; hint: string; type: 'text' | 'number' | 'select'; currency?: boolean; options?: { value: string; label: string }[]; show?: (a: Answers) => boolean }
const questions: Question[] = [
  { key: 'purpose', label: 'What will this loan do for you?', hint: 'A plain-language purpose helps separate useful debt from expensive wants.', type: 'text' },
  { key: 'loanType', label: 'Which loan are you considering?', hint: 'The product changes the fair rate and the security a lender should ask for.', type: 'select', options: [{ value: 'personal', label: 'Personal loan' }, { value: 'business', label: 'Business / stock' }, { value: 'two-wheeler', label: 'Two-wheeler / e-scooter' }, { value: 'lap', label: 'Loan against property' }, { value: 'gold', label: 'Gold loan' }] },
  { key: 'wanted', label: 'How much do you want to borrow?', hint: 'Enter the amount you would put on the sanction letter.', type: 'number', currency: true },
  { key: 'income', label: 'What reaches your account in a normal month?', hint: 'Use take-home income, not CTC. For variable income, use a conservative average.', type: 'number', currency: true },
  { key: 'incomeType', label: 'How is that income earned?', hint: 'This affects how much income a lender may count.', type: 'select', options: [{ value: 'salaried', label: 'Salaried' }, { value: 'self-employed', label: 'Self-employed / business' }, { value: 'informal', label: 'Informal or gig income' }] },
  { key: 'existingEmi', label: 'How much do existing loan EMIs cost each month?', hint: 'Include app loans, credit card conversions, and buy-now-pay-later.', type: 'number', currency: true },
  { key: 'expenses', label: 'What do essentials cost each month?', hint: 'Rent, food, school, utilities, transport and support for family. Leave loan EMIs out.', type: 'number', currency: true },
  { key: 'age', label: 'How old are you?', hint: 'Age affects the maximum practical tenure, not your worthiness.', type: 'number' },
  { key: 'scoreKnown', label: 'Do you know your credit score?', hint: 'Unknown is okay. It will make the rate range wider, never zero.', type: 'select', options: [{ value: 'yes', label: 'Yes, I know it' }, { value: 'no', label: "No, I don't know" }] },
  { key: 'score', label: 'What is your score?', hint: 'Use the latest score you have seen, not a guess.', type: 'number', show: (a) => a.scoreKnown === 'yes' },
  { key: 'incomeHistory', label: 'How long has this income been steady?', hint: 'The longer the trail, the more of it a lender can usually verify.', type: 'select', options: [{ value: 'under-1', label: 'Less than 1 year' }, { value: '1-3', label: '1–3 years' }, { value: '3-plus', label: 'More than 3 years' }, { value: 'variable', label: 'It changes a lot month to month' }], show: (a) => a.incomeType !== 'salaried' },
  { key: 'emergencySavings', label: 'How many months of essentials are saved?', hint: 'This changes your stress ceiling: savings buy you time when income falls.', type: 'number' },
  { key: 'variableShare', label: 'What share of income is variable?', hint: 'Commission, cash sales or incentives. Enter 0 if your pay is fixed.', type: 'number', show: (a) => a.incomeType !== 'salaried' },
  { key: 'coApplicant', label: 'Will a co-applicant with provable income join?', hint: 'Only count income they would actually sign up to repay.', type: 'select', options: [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }] },
  { key: 'collateral', label: 'What is the approximate value of property offered as security?', hint: 'Enter 0 if you do not want to pledge property.', type: 'number', currency: true, show: (a) => a.loanType === 'business' || a.loanType === 'lap' },
  { key: 'bounces', label: 'Any EMI or auto-debit bounce in the last 6 months?', hint: 'A bounce is a real warning signal, not a moral judgement.', type: 'select', options: [{ value: 'none', label: 'No' }, { value: 'one', label: 'One' }, { value: 'multiple', label: 'More than one' }] },
  { key: 'processingFee', label: 'What processing fee has been quoted?', hint: 'Use the percentage, before GST. If no quote, keep the 1.5% estimate.', type: 'number' },
  { key: 'offeredRate', label: 'Has anyone offered you a rate yet?', hint: 'Optional. It lets your card show the gap between a quote and a fair band.', type: 'number' },
]
const scenarios: { name: string; meta: string; answers: Partial<Answers> }[] = [
  { name: 'Priya', meta: 'Salaried · Bengaluru · personal loan', answers: { purpose: 'Wedding costs', loanType: 'personal', wanted: 800000, income: 110000, incomeType: 'salaried', existingEmi: 14000, expenses: 68000, age: 29, scoreKnown: 'yes', score: 780, emergencySavings: 4, variableShare: 0, coApplicant: 'no', bounces: 'none', processingFee: 1.5, tenure: 36 } },
  { name: 'Ravi', meta: 'Self-employed · Mysuru · business loan', answers: { purpose: 'Second stock line and delivery vehicle', loanType: 'business', wanted: 1500000, income: 60000, incomeType: 'self-employed', existingEmi: 0, expenses: 32000, age: 42, scoreKnown: 'no', score: 0, incomeHistory: '3-plus', emergencySavings: 3, variableShare: 40, coApplicant: 'yes', collateral: 4500000, bounces: 'none', processingFee: 1.25, tenure: 60 } },
  { name: 'Anita', meta: 'Informal · Hubballi · e-scooter loan', answers: { purpose: 'Electric scooter for more delivery runs', loanType: 'two-wheeler', wanted: 150000, income: 28000, incomeType: 'informal', existingEmi: 6000, expenses: 18500, age: 35, scoreKnown: 'no', score: 0, incomeHistory: 'variable', emergencySavings: 0, variableShare: 35, coApplicant: 'no', bounces: 'one', processingFee: 2, tenure: 36 } },
]

function App() {
  const [answers, setAnswers] = useState<Answers>(emptyAnswers)
  const [started, setStarted] = useState(false)
  const [step, setStep] = useState(0)
  const [showResult, setShowResult] = useState(false)
  const visibleQuestions = useMemo(() => questions.filter((q) => !q.show || q.show(answers)), [answers])
  const current = visibleQuestions[step]
  const result = useMemo(() => assess(answers), [answers])
  const update = (value: string) => setAnswers((old) => ({ ...old, [current.key]: current.type === 'number' ? Number(value) : value }))
  const useScenario = (scenario: typeof scenarios[number]) => { setAnswers({ ...emptyAnswers, ...scenario.answers }); setStarted(true); setShowResult(true) }
  const start = () => { setStarted(true); setShowResult(false); setStep(0) }
  const next = () => { if (step < visibleQuestions.length - 1) setStep(step + 1); else setShowResult(true) }
  const reset = () => { setAnswers(emptyAnswers); setStarted(false); setShowResult(false); setStep(0) }
  if (!started) return <Landing onStart={start} onScenario={useScenario} />
  if (showResult) return <Results answers={answers} result={result} onBack={() => setShowResult(false)} onReset={reset} />
  const value = answers[current.key]
  const progress = Math.round(((step + 1) / visibleQuestions.length) * 100)
  return <main className="app-shell assessment-shell"><Topbar onReset={reset} /><div className="assessment-layout"><aside className="side-rail"><span className="eyebrow">YOUR ASSESSMENT</span><h2>Make the numbers earn your trust.</h2><p>Answer the essentials first. The follow-ups only appear when they change the advice.</p><div className="privacy-note"><span>✦</span><div><strong>Private by design</strong><br />No login. Nothing leaves this device.</div></div></aside><section className="question-panel"><div className="progress-row"><span>Question {step + 1} of {visibleQuestions.length}</span><span>{progress}%</span></div><div className="progress-track"><span style={{ width: `${progress}%` }} /></div><div className="question-body"><span className="question-kicker">{step < 10 ? 'CORE QUESTION' : 'TIGHTEN THE RANGE'}</span><h1>{current.label}</h1><p className="question-hint">{current.hint}</p>{current.type === 'text' && <input autoFocus value={String(value || '')} onChange={(e) => update(e.target.value)} placeholder="e.g. combine two high-interest loans" />}{current.type === 'number' && (current.currency ? <div className="input-with-prefix"><span>₹</span><input autoFocus type="number" value={Number(value) || ''} onChange={(e) => update(e.target.value)} placeholder="0" /></div> : <input autoFocus type="number" value={Number(value) || ''} onChange={(e) => update(e.target.value)} placeholder="0" />)}{current.type === 'select' && <div className="option-grid">{current.options?.map((option) => <button key={option.value} className={value === option.value ? 'option selected' : 'option'} onClick={() => update(option.value)}>{option.label}<span>{value === option.value ? '✓' : '→'}</span></button>)}</div>}</div><div className="question-actions"><button className="text-button" onClick={() => step > 0 && setStep(step - 1)} disabled={step === 0}>Back</button><button className="primary-button" onClick={next}>{step === visibleQuestions.length - 1 ? 'See my numbers' : 'Continue'} <span>→</span></button></div></section></div></main>
}

function Landing({ onStart, onScenario }: { onStart: () => void; onScenario: (scenario: typeof scenarios[number]) => void }) { return <main className="app-shell landing"><Topbar /><section className="hero-grid"><div className="hero-copy"><span className="eyebrow">BORROWER COPILOT · INDIA</span><h1>Walk in knowing<br /><em>your number.</em></h1><p className="hero-lede">A private, plain-English second opinion before you meet a lender. Know what you can carry, what is fair, and what to say across the desk.</p><button className="primary-button hero-button" onClick={onStart}>Build my borrower card <span>→</span></button><div className="hero-meta"><span>◎ Takes 4 minutes</span><span>◎ No login or bureau pull</span></div></div><div className="hero-art"><div className="sun-disc" /><div className="art-card card-back">₹ 22,000<span>safe EMI</span></div><div className="art-card card-front"><span className="mini-label">YOUR FAIR RATE</span><strong>11.0–12.5%</strong><div className="art-line" /><span className="art-foot">Because your score is 780</span></div><div className="orbit orbit-one" /><div className="orbit orbit-two" /></div></section><section className="scenario-strip"><div><span className="eyebrow">SEE IT IN ACTION</span><h2>Start with a real borrower</h2></div>{scenarios.map((scenario) => <button className="scenario" key={scenario.name} onClick={() => onScenario(scenario)}><span className="scenario-name">{scenario.name}</span><span>{scenario.meta}</span><b>↗</b></button>)}</section><section className="promise-row"><div><span>01</span><strong>Borrow or pause</strong><p>A verdict you can act on, including “don't borrow”.</p></div><div><span>02</span><strong>Two honest ceilings</strong><p>Lender sanction versus what your life can safely carry.</p></div><div><span>03</span><strong>One-page leverage</strong><p>A negotiation card with rate, APR and your why.</p></div></section></main> }
function Topbar({ onReset }: { onReset?: () => void }) { return <header className="topbar"><button className="brand" onClick={onReset}><span className="brand-mark">⌁</span><span>Borrower <b>Copilot</b></span></button><span className="topbar-note">Your side of the table <span>✦</span></span></header> }
function Results({ answers, result, onBack, onReset }: { answers: Answers; result: ReturnType<typeof assess>; onBack: () => void; onReset: () => void }) { const [tab, setTab] = useState<'overview' | 'card'>('overview'); return <main className="app-shell results-shell"><Topbar onReset={onReset} /><div className="results-head"><div><span className="eyebrow">YOUR BORROWER BRIEF</span><h1>{result.verdictTitle}</h1><p>{result.verdictReason}</p></div><div className={`verdict-badge ${result.verdict}`}><span>{result.verdict === 'dont' ? '!' : result.verdict === 'borrow-less' ? '↘' : '✓'}</span>{result.verdict === 'dont' ? 'Pause' : result.verdict === 'borrow-less' ? 'Borrow less' : 'Can fit'}</div></div><div className="result-toolbar"><div className="tabs"><button className={tab === 'overview' ? 'active' : ''} onClick={() => setTab('overview')}>Four answers</button><button className={tab === 'card' ? 'active' : ''} onClick={() => setTab('card')}>Negotiation card</button></div><span className="confidence">{result.confidence} confidence <i>i</i></span></div>{tab === 'overview' ? <><section className="metric-grid"><Metric label="Lender may sanction" value={formatINR(result.lenderMax)} note={`At up to ${formatINR(result.lenderEmi)} EMI`} accent="orange" /><Metric label="You should use" value={formatINR(result.safeMax)} note={`Keep EMI under ${formatINR(result.safeEmi)}`} accent="teal" recommended /><Metric label="Fair interest band" value={`${result.fairRate[0].toFixed(1)}–${result.fairRate[1].toFixed(1)}%`} note={`APR with fees: ${result.apr[0].toFixed(1)}–${result.apr[1].toFixed(1)}%`} accent="blue" /><Metric label="Stress ceiling" value={formatINR(result.stressSafeMax)} note="Income -22% or rate +2 pts" accent="plum" /></section><section className="explain-grid"><div className="explain-panel"><div className="panel-heading"><span className="eyebrow">WHY THESE NUMBERS</span><span className="product-pill">{result.productLabel}</span></div>{result.reasons.map((reason) => <div className="reason" key={reason}><span>✦</span><p>{reason}</p></div>)}<p className="confidence-note">{result.confidenceNote} Ranges are deliberately wider where information is missing.</p></div><div className="action-panel"><span className="eyebrow">NEXT MOVE</span><h3>{result.verdict === 'dont' ? 'Protect your cash flow first.' : 'Take this ceiling to the branch.'}</h3><p>{result.verdict === 'dont' ? 'Ask for a statement of all three app loans, stop new borrowing, and build one month of essentials.' : `A lender's maximum is not your budget. Start negotiations at ${formatINR(result.safeMax)}, not ${formatINR(result.lenderMax)}.`}</p><button className="secondary-button" onClick={() => setTab('card')}>Open negotiation card ↗</button></div></section></> : <NegotiationCard answers={answers} result={result} onBack={onBack} />}</main> }
function Metric({ label, value, note, accent, recommended }: { label: string; value: string; note: string; accent: string; recommended?: boolean }) { return <article className={`metric-card ${accent} ${recommended ? 'recommended' : ''}`}>{recommended && <span className="recommended-label">USE THIS ONE</span>}<span className="metric-label">{label}</span><strong>{value}</strong><span className="metric-note">{note}</span></article> }
function NegotiationCard({ answers, result, onBack }: { answers: Answers; result: ReturnType<typeof assess>; onBack: () => void }) { return <section className="card-view"><div className="negotiation-card"><div className="card-top"><span className="eyebrow">BORROWER COPILOT · NEGOTIATION CARD</span><span>Prepared today</span></div><div className="card-title"><h2>My fair deal</h2><p>{result.productLabel} for {answers.purpose || 'my stated purpose'}</p></div><div className="card-stats"><div><span>Fair rate</span><strong>{result.fairRate[0].toFixed(1)}–{result.fairRate[1].toFixed(1)}%</strong></div><div><span>All-in APR</span><strong>{result.apr[0].toFixed(1)}–{result.apr[1].toFixed(1)}%</strong></div><div><span>My EMI ceiling</span><strong>{formatINR(result.safeEmi)}</strong></div></div><div className="card-rule" /><div className="card-ask"><span className="quote-mark">“</span><div><h3>What I will say</h3>{result.negotiation.map((line) => <p key={line}>{line}</p>)}</div></div><div className="card-footer"><span>My safe amount: <b>{formatINR(result.safeMax)}</b></span><span>Stress amount: <b>{formatINR(result.stressSafeMax)}</b></span></div></div><div className="card-actions"><button className="text-button" onClick={onBack}>← Edit answers</button><button className="secondary-button" onClick={() => window.print()}>Print / save card</button></div></section> }
export default App
